language: node_js
sudo: false
node_js:
  - "7.5"

before_script:
  - curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - dpkg -i google-chrome.deb
  - sleep 3
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - nohup bash -c "yarn run webdriver-update"
  - nohup bash -c "yarn run webdriver-start 2>&1 &"

script:
  - yarn test

after_success:
  - coveralls